trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - $(build.sourcedirectory)/.azdeploy/environments/nonprod/global/*
      
pool: 
  vmImage: ubuntu-latest

variables:
  environment: 'Dev'
  key_vault_name: 'sunrisekeyvaulteastus'
  key_vault_rgname: 'POH'

stages:
  - stage: Terraform_${{ variables.environment }}
    displayName: "Terraform Provisioning - ${{ variables.environment }}"
    jobs:
      - job: terraform_provisioning
        displayName: "Deploy resources - Terraform"
        timeoutInMinutes: 180
        steps:
          - task: Bash@3
            displayName: 'Set Environment Variable'
            enabled: true
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[task.setvariable variable=TF_VAR_KEY_VAULT_NAME;]${{ variables.key_vault_name }}"
                echo "##vso[task.setvariable variable=TF_VAR_KEY_VAULT_RGNAME;]${{ variables.key_vault_rgname }}"
          - template: terraform-deploy.yml
            parameters:
              working_dir: "$(Build.SourcesDirectory)/terraform/environment/nonprod/global"
              serviceconn_name : "FreeAzureDevOpsSPN"
              tfresourcegroupname : "POH"
              tfstorageaccountname : "sunriseappeastus"
              azureRmContainerName : "sunrise-prod-tfstate"
              tfstatefile : "poh-global-demo.tfstate"

  - stage: Deployment_Dacpac
    condition: and(succeeded(), eq(variables['TerraformApply'], 'True'))
    displayName: Download and deployment of dacpac
    jobs:
      - job: Download_and_Deploy_DacPac
        pool:
          vmImage: windows-latest
        displayName: Download & Deploy publish Dacpac
        steps:
          - task: AzureKeyVault@2
            inputs:
              azureSubscription: "FreeAzureDevOpsSPN"
              KeyVaultName: '${{ variables.key_vault_name }}'
              SecretsFilter: '*'
              RunAsPreJob: false  

          - task: DownloadBuildArtifacts@1
            displayName: Download artifacts
            inputs:
              buildType: 'specific'
              project: 'ac67152a-86b2-439f-b425-33411329a8ec'
              pipeline: '10564'
              specificBuildWithTriggering: true
              buildVersionToDownload: 'latest'
              downloadType: 'single'
              artifactName: 'DacPac'
              downloadPath: '$(Build.ArtifactStagingDirectory)'

          - task: SqlAzureDacpacDeployment@1
            displayName: Deploy Dacpac
            enabled: true
            inputs:
              azureSubscription: 'poh-services-nonprod-Platform of Health'
              ServerName: $(globalSQLservername)
              DatabaseName: $(globalSQLDBname)
              SqlUsername: $(serverUsername)
              SqlPassword: $(serverPassword)
              DacpacFile: '$(Build.ArtifactStagingDirectory)/DacPac/POHTenancy.dacpac'