trigger: none
pr:
  branches:
    include:
      - main
  paths:
    include:
      - $(build.sourcedirectory)/.azdeploy/environments/nonprod/global/*
      
pool: 
  vmImage: ubuntu-latest

variables:
  environment: Dev
  key_vault_name: sunriseprodeastus
  key_vault_rgname: POH

stages:
  - stage: Terraform_${{ variables.environment }}
    displayName: "Terraform Provisioning - ${{ variables.environment }}"
    jobs:
      - job: terraform_provisioning
        displayName: "Deploy resources - Terraform"
        timeoutInMinutes: 180
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureDevOpsDemoSPN'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az login
                az account set --subscription 2daf7420-f7f4-4e0f-8a65-8dd8f147545b
          - task: Bash@3
            displayName: 'Set Environment Variable'
            enabled: true
            inputs:
              targetType: 'inline'
              script: |
                echo "##vso[task.setvariable variable=TF_VAR_KEY_VAULT_NAME;]${{ variables.key_vault_name }}"
                echo "##vso[task.setvariable variable=TF_VAR_KEY_VAULT_RGNAME;]${{ variables.key_vault_rgname }}"
          - template: terraform-deploy.yml
            parameters:
              working_dir: "$(Build.SourcesDirectory)/terraform/environment/nonprod/global"
              serviceconn_name : "AzureDevOpsDemoSPN"
              tfresourcegroupname : "POH"
              tfstorageaccountname : "sunriseappeastus"
              azureRmContainerName : "sunriseprodtfstate"
              tfstatefile : "poh-global-demo.tfstate"
