name: Deploy POH Service

on: 
   workflow_dispatch:
      inputs:
         RingInfo:
            description: "RingInfo"
            required: true

jobs:
  
  createGithubWorkFlow:
    runs-on: windows-latest
    steps:
      - name: checkout action files
        uses: actions/checkout@v2 
      - name : Create Github WorkFlow for POH Service Deployment     
        shell: powershell
        run: |
             .\Scripts\createGithubWorflow.ps1 -Token '${{ secrets.MYAPPTOKEN }}' -RingInfo '${{ inputs.RingInfo }}'


  Job1:
    runs-on: ubuntu-latest
    needs: createGithubWorkFlow
    steps:
      - name: checkout action files
        uses: actions/checkout@v2 
      - name : Job1     
        shell: pwsh
        run: |
              Write-Host "Job1 Completed"

              

  Job2:
    runs-on: ubuntu-latest
    needs: [createGithubWorkFlow, Job1] 
    if: ${{ always() }}
    steps:
    
      - name: checkout action files
        uses: actions/checkout@v2 
        
      - name : Update POH Service Deployment Status on Azure SQL Database 
        shell: pwsh
        run: |
              [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
              Install-Module -Name SqlServer -Scope CurrentUser -AllowClobber -Force -ErrorAction Stop -Confirm:$false 
              $deploymentDate = Get-Date -Format "MM/dd/yyyy hh:mm tt"
              $deploymentStatus = "${{ needs.Job1.result }}"
              $deploymentURL = "https://github.com/jayeshkumarpatel2611/MyApp/actions/runs/${{ github.run_id }}"
              Write-Host "Date: " $deploymentDate
              Write-Host "Status: " $deploymentStatus
              Write-Host "URL: " $deploymentURL
           
              Write-Host "---------------------------------------------------------------------------------------"
              $sqlQuery = "UPDATE [dbo].[POH] SET ServiceDeploymentDate = '$deploymentDate', ServiceDeploymentStatus = '$deploymentStatus', ServiceDeploymentURL = '$deploymentURL' WHERE TenantID = '72eb4a65-023a-419c-8a36-64b05564b71f'"
              Invoke-sqlCmd -ConnectionString "${{ secrets.SQL_Connection_String }}" -query "$($sqlQuery)"
              
  
