name: Deployment template - Non Prod

on: 
   workflow_call:
      inputs:
         dotnetRuntimes:
            description: "dotnet frameworks which need to be install like dotnet-hosting-2.1.28-win,dotnet-hosting-3.1.16-win"
            required: true
            type: string
         EnvironmentName:
            description: "Environment Name"
            required: true
            type: string
         HCServer:
            description: "HC Environment Name"
            required: true
            type: string
         metaFileReleaseJson:
            description: "Version of the metajson"
            required: true
            type: string
         requiredHeliosConnectVersion:
            description: "Version of the HeliosConnect"
            required: true
            type: string
         requiredEnterpriseManagerVersion:
            description: "Version of the EnterpriseManager"
            required: true
            type: string
         sqlServer:
            description: "sqlServer"
            required: true
            type: string 
         sqlDatabase:
            description: "sqlDatabase"
            required: true
            type: string 

jobs:

  HC-PreCheck:
   runs-on: ${{ inputs.HCServer }}
   steps:
      - run: echo "This job is now running on a ${{ runner.os }}."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "This job's status is ${{ job.status }}."
      - name: checkout action files
        uses: actions/checkout@v2    
      - name : Install Prerequisites for HC Deployments      
        shell: powershell
        run : |
                Scripts\ValidationScript.ps1 -validationFor "HC" -validationType "Pre" -dotnetRuntimes "${{ inputs.dotnetRuntimes }}" -EnvironmentName "${{ inputs.EnvironmentName }}" -metaFileReleaseJson "${{ inputs.metaFileReleaseJson }}" -ValidationScriptModulePath "./Scripts/ValidationScriptModule.psm1" -requiredHeliosConnectVersion "${{ inputs.requiredHeliosConnectVersion }}" -requiredEnterpriseManagerVersion "${{ inputs.requiredEnterpriseManagerVersion }}" -sqlServer "${{ inputs.sqlServer }}" -sqlDatabase "${{ inputs.sqlDatabase }}" 
                
      - name: Upload Logs
        uses: actions/upload-artifact@v2
        with: 
          name: upload-logs
          path: C:\Logs
