on: 
   workflow_dispatch:
      inputs:
         dotnetruntimes:
            description: ".Net Frameworks"
            required: true
            default: "dotnet-hosting-2.1.28-win,dotnet-hosting-3.1.16-win"
            
         deploymentType:
            description: "Wheter Precheck is for HC or HWS"
            required: true
            default: "HWS"
            
jobs:
  HWS-PreCheck:
    runs-on: [self-hosted, SunriseAir]
    steps:
      - run: echo "This job is now running on a ${{ runner.os }}."
      - run: echo "The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "This job's status is ${{ job.status }}."
      - name: checkout action files
        uses: actions/checkout@v2    
      - name : Install Prerequisites for HWS Deployments      
        shell: powershell
        run : |
                Scripts\Install_Prerequisites.ps1 -dotnetruntimes "${{ github.event.inputs.dotnetruntimes }}" -DeploymentType ${{ github.event.inputs.deploymentType }}             
 
  HWS-Deployment:
    runs-on: [self-hosted, SunriseAir]
    needs: HWS-PreCheck
    steps:
      - run: echo "Starting HWS - Deployment"
      - name: SQL Installer
        shell: powershell          
        run: |  
               Scripts\deployments.ps1
