name: Ring0 POH Services Deployment
on:
   workflow_dispatch:

jobs:
   Ring_0:
      runs-on: ubuntu-latest
      environment: 'poh-services-prod-ring0'
      steps:
         - run: echo "Ring_0 Approved"

   US_Region:
      runs-on: ubuntu-latest
      needs: Ring_0
      steps:
         - run: echo "US_Region_Region Approved"

   EastUS2_Location:
      runs-on: ubuntu-latest
      needs: US_Region
      steps:
         - run: echo "EastUS2_Location_Location Approved"
         
   CentralUS_Location:
      runs-on: ubuntu-latest
      needs: US_Region
      steps:
         - run: echo "CentralUS_Location_Location Approved"

   Client_Development:
      runs-on: ubuntu-latest
      needs: EastUS2_Location
      steps:
         - run: echo "Client_Development Approved"

   Client_Test_UAT:
      runs-on: ubuntu-latest
      needs: CentralUS_Location
      steps:
         - run: echo "Client_Test_UAT Approved"

   Client_Development_001:
    uses: ./.github/workflows/deployment-template_prod.yml
    needs: Client_Development
    with:
      ringLevel: "Ring_0"
      serviceHost: ""
      appDomainAccount: ""
      envName: ""
      HWSServer: ""
      HCServer: ""
      approvalStageEnv: "poh-env-prod-eg-clientdev_eastus2"
      POHTenantID: ""
      IDNTenantID: ""
      POHBASEURL: ""
      envCode: "4"
      clientName: ""
      clientEnvName: "DevOpsTest"
      metajsonfile: "poh-services-metadata.json"
      AppsToDeploy: "DeployAll"
      SDRM: $False
      isRestore: $False
      DevopsKeyVault: "poh-0-durable-kv"
      GlobalKeyVault: "poh-0-global-kv"
      HCPhysicalPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\Helios\\8.7\\HeliosConnect"
      HWSPhysicalPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\POH"
      EnterpriseMangerPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\Enterprise Manager"
      VirtualConnectionPath: "HeliosConnect/87"
    secrets:
      AZURE_DEVOPS_PAT_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT_TOKEN }}

   Client_Test_001:
    uses: ./.github/workflows/deployment-template_prod.yml
    needs: Client_Test_UAT
    with:
      ringLevel: "Ring_0"
      serviceHost: ""
      appDomainAccount: ""
      envName: ""
      HWSServer: ""
      HCServer: ""
      approvalStageEnv: "poh-env-prod-eg-clientdev_eastus2"
      POHTenantID: ""
      IDNTenantID: ""
      POHBASEURL: ""
      envCode: "4"
      clientName: ""
      clientEnvName: "DevOpsTest"
      metajsonfile: "poh-services-metadata.json"
      AppsToDeploy: "DeployAll"
      SDRM: $False
      isRestore: $False
      DevopsKeyVault: "poh-0-durable-kv"
      GlobalKeyVault: "poh-0-global-kv"
      HCPhysicalPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\Helios\\8.7\\HeliosConnect"
      HWSPhysicalPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\POH"
      EnterpriseMangerPath: "C:\\Program Files (x86)\\Allscripts Sunrise\\Enterprise Manager"
      VirtualConnectionPath: "HeliosConnect/87"
    secrets:
      AZURE_DEVOPS_PAT_TOKEN: ${{ secrets.AZURE_DEVOPS_PAT_TOKEN }}

