name: Validate
on: 
   workflow_dispatch:

jobs:
   PowerShell_Validation_Script_Test:
    uses: ./.github/workflows/deployment-template_nonprod.yml
    with: 
      dotnetRuntimes: "2.1.28,3.1.16"
      EnvironmentName: "Demo"
      metaFileReleaseJson: "./Scripts/json/poh-services-metadata.json"
      requiredHeliosConnectVersion: "2.1.19"
      requiredEnterpriseManagerVersion: "2.1.19"
      HCServer: "myserver01"
      sqlServer: "myserver01"
      sqlDatabase: "MyDB"


    
